language: java
sudo: false
jdk:
- oraclejdk8

before_deploy:
- mvn clean package

deploy:
  - provider: bintray
    file: bintray.json
    user: tomschi
    key: $BINTRAY_API_KEY
    dry-run: false
    on: v0.1.x

  - provider: bintray
    file: commons-data-test/target/deploy-descriptors/bintray.json
    user: tomschi
    key: $BINTRAY_API_KEY
    dry-run: false
    on: v0.1.x